// Generated by CodiumAI

const { getDomainName } = require("./helper");

describe("getDomainName", () => {
  // Returns the correct domain name for a request with x-forwarded-host header
  it("should return the correct domain name when x-forwarded-host header is present", () => {
    const req = {
      headers: {
        "x-forwarded-host": "example.com",
      },
      protocol: "https",
      headers: {
        host: "localhost:3000",
      },
    };

    const result = getDomainName(req);

    expect(result).toBe("https://localhost:3000");
  });

  // Returns the correct domain name for a local request
  it("should return the correct domain name for a local request", () => {
    const req = {
      headers: {},
      protocol: "http",
      headers: {
        host: "localhost:3000",
      },
    };

    const result = getDomainName(req);

    expect(result).toBe("http://localhost:3000");
  });
});
