// Generated by CodiumAI

const { loginUser } = require("./auth.controller");
const helper = require("../../helper/helper");

describe("loginUser", () => {
  // Returns a 200 status code with the email, password, and key when valid email and password are provided in the request body.
  it("should return a 200 status code with the email, password, and key when valid email and password are provided", () => {
    const req = {
      body: {
        email: "test@example.com",
        password: "password123",
      },
    };
    const res = {
      status: jest.fn().mockReturnThis(),
      json: jest.fn(),
    };

    loginUser(req, res);

    expect(res.status).toHaveBeenCalledWith(200);
    expect(res.json).toHaveBeenCalledWith({
      email: "test@example.com",
      password: "password123",
      key: "001",
    });
  });

  it("should return a 400 status code with an error message when email is not a string", () => {
    const req = {
      body: {
        email: "",
        password: "",
      },
    };
    const res = {
      status: jest.fn().mockReturnThis(),
      json: jest.fn(),
    };

    loginUser(req, res);

    expect(res.status).toHaveBeenCalledWith(400);
    expect(res.json).toHaveBeenCalledWith({
      code: 400,
      data: [],
      errors: [
        {
          msg: "Username and password is required",
        },
      ],
      status: "Internal Server Error",
    });
  });
});
